---
# tasks file for java

- name: Install Java
  include: Debian.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'


- name: Install Java
  include: Redhat.yml
  when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'

