---

#install java kit
- name: Ensure Java Development Kit is Installed
  become: true
  yum: 
    pkg: java-1.8.0-openjdk-devel
    state: installed
  tags: java_installlation

- name: get the java_path
  shell: sudo update-java-alternatives -l | awk '{print $3}'
  register: java_path
  tags: getting_java_home

- name: Add ElasticSearch GPG key
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Elastic Reposirtory for 5.x packages
  copy: 
    src: https://artifacts.elastic.co/packages/5.x/yum
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0644

- name: Install Logstash.
  yum: 
    pkg: Logstash 
    state: installed
